package com.bca.minibank.model;

import java.util.Date;


import com.bca.minibank.entity.TbTransaksi;
import com.bca.minibank.form.FormTransaksi;

/**
 * TbTransaksi generated by hbm2java
 */

public class ModelTransaksi {

	private String noRek;
	private Integer nominal;
	
	public ModelTransaksi(FormTransaksi formTransaksi){
		this.nominal = formTransaksi.getNominal();
		this.noRek = formTransaksi.getNoRek();
	}
	
	
	public String getNoRek() {
		return noRek;
	}
	public void setNoRek(String noRek) {
		this.noRek = noRek;
	}
	public Integer getNominal() {
		return nominal;
	}
	public void setNominal(Integer Nominal) {
		this.nominal = Nominal;
	}
	
	
	
}
