package com.bca.minibank.entity;
// Generated Apr 24, 2020 11:11:46 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbJnsTab generated by hbm2java
 */
@Entity
@Table(name = "TB_JNS_TAB")
public class TbJnsTab implements java.io.Serializable {

	private int idJnsTab;
	private String namaJnsTab;
	private int biayaAdmin;
	private int limitTransaksi;
	private double bunga;
	private Set<TbRekening> tbRekenings = new HashSet<TbRekening>(0);

	public TbJnsTab() {
	}

	public TbJnsTab(int idJnsTab, String namaJnsTab, int biayaAdmin, int limitTransaksi,
			double bunga) {
		this.idJnsTab = idJnsTab;
		this.namaJnsTab = namaJnsTab;
		this.biayaAdmin = biayaAdmin;
		this.limitTransaksi = limitTransaksi;
		this.bunga = bunga;
	}

	public TbJnsTab(int idJnsTab, String namaJnsTab, int biayaAdmin, int limitTransaksi,
			double bunga, Set<TbRekening> tbRekenings) {
		this.idJnsTab = idJnsTab;
		this.namaJnsTab = namaJnsTab;
		this.biayaAdmin = biayaAdmin;
		this.limitTransaksi = limitTransaksi;
		this.bunga = bunga;
		this.tbRekenings = tbRekenings;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID_JNS_TAB", unique = true, nullable = false, precision = 22, scale = 0)
	public int getIdJnsTab() {
		return this.idJnsTab;
	}

	public void setIdJnsTab(int idJnsTab) {
		this.idJnsTab = idJnsTab;
	}

	@Column(name = "NAMA_JNS_TAB", nullable = false, length = 15)
	public String getNamaJnsTab() {
		return this.namaJnsTab;
	}

	public void setNamaJnsTab(String namaJnsTab) {
		this.namaJnsTab = namaJnsTab;
	}

	@Column(name = "BIAYA_ADMIN", nullable = false, precision = 22, scale = 0)
	public int getBiayaAdmin() {
		return this.biayaAdmin;
	}

	public void setBiayaAdmin(int biayaAdmin) {
		this.biayaAdmin = biayaAdmin;
	}

	@Column(name = "LIMIT_TRANSAKSI", nullable = false, precision = 22, scale = 0)
	public int getLimitTransaksi() {
		return this.limitTransaksi;
	}

	public void setLimitTransaksi(int limitTransaksi) {
		this.limitTransaksi = limitTransaksi;
	}

	@Column(name = "BUNGA", nullable = false, precision = 126, scale = 0)
	public double getBunga() {
		return this.bunga;
	}

	public void setBunga(double bunga) {
		this.bunga = bunga;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbJnsTab")
	public Set<TbRekening> getTbRekenings() {
		return this.tbRekenings;
	}

	public void setTbRekenings(Set<TbRekening> tbRekenings) {
		this.tbRekenings = tbRekenings;
	}

}
