package com.bca.minibank.entity;
// Generated Apr 24, 2020 11:11:46 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbLogAdmin generated by hbm2java
 */
@Entity
@Table(name = "TB_LOG_ADMIN")
public class TbLogAdmin implements java.io.Serializable {

	private int idLog;
	private TbUsers tbUsers;
	private String action;
	private int toIdUser;
	private int toIdTransaksi;
	private Date tglLog;

	public TbLogAdmin() {
	}

	public TbLogAdmin(int idLog, TbUsers tbUsers, String action, int toIdUser, Date tglLog) {
		this.idLog = idLog;
		this.tbUsers = tbUsers;
		this.action = action;
		this.toIdUser = toIdUser;
		this.tglLog = tglLog;
	}

	public TbLogAdmin(int idLog, TbUsers tbUsers, String action, int toIdUser, int toIdTransaksi,
			Date tglLog) {
		this.idLog = idLog;
		this.tbUsers = tbUsers;
		this.action = action;
		this.toIdUser = toIdUser;
		this.toIdTransaksi = toIdTransaksi;
		this.tglLog = tglLog;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID_LOG", unique = true, nullable = false, precision = 22, scale = 0)
	public int getIdLog() {
		return this.idLog;
	}

	public void setIdLog(int idLog) {
		this.idLog = idLog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USER", nullable = false)
	public TbUsers getTbUsers() {
		return this.tbUsers;
	}

	public void setTbUsers(TbUsers tbUsers) {
		this.tbUsers = tbUsers;
	}

	@Column(name = "ACTION", nullable = false, length = 7)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "TO_ID_USER", nullable = false, precision = 22, scale = 0)
	public int getToIdUser() {
		return this.toIdUser;
	}

	public void setToIdUser(int toIdUser) {
		this.toIdUser = toIdUser;
	}

	@Column(name = "TO_ID_TRANSAKSI", precision = 22, scale = 0)
	public int getToIdTransaksi() {
		return this.toIdTransaksi;
	}

	public void setToIdTransaksi(int toIdTransaksi) {
		this.toIdTransaksi = toIdTransaksi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TGL_LOG", nullable = false, length = 11)
	public Date getTglLog() {
		return this.tglLog;
	}

	public void setTglLog(Date tglLog) {
		this.tglLog = tglLog;
	}

}
