package com.bca.minibank.entity;
// Generated Apr 24, 2020 11:11:46 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbMutasi generated by hbm2java
 */
@Entity
@Table(name = "TB_MUTASI")
public class TbMutasi implements java.io.Serializable {

	private int idMutasi;
	private TbTransaksi tbTransaksi;
	private String jnsMutasi;
	private int nominal;
	private double saldoAkhir;
	private String note;
	private Date tglMutasi;
	private String noRek;

	public TbMutasi() {
	}

	public TbMutasi(int idMutasi, TbTransaksi tbTransaksi, String jnsMutasi, int nominal,
			double saldoAkhir, String note, Date tglMutasi) {
		this.idMutasi = idMutasi;
		this.tbTransaksi = tbTransaksi;
		this.jnsMutasi = jnsMutasi;
		this.nominal = nominal;
		this.saldoAkhir = saldoAkhir;
		this.note = note;
		this.tglMutasi = tglMutasi;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID_MUTASI", unique = true, nullable = false, precision = 22, scale = 0)
	public int getIdMutasi() {
		return this.idMutasi;
	}

	public void setIdMutasi(int idMutasi) {
		this.idMutasi = idMutasi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TRANSAKSI", nullable = false)
	public TbTransaksi getTbTransaksi() {
		return this.tbTransaksi;
	}

	public void setTbTransaksi(TbTransaksi tbTransaksi) {
		this.tbTransaksi = tbTransaksi;
	}

	@Column(name = "JNS_MUTASI", nullable = false, length = 11)
	public String getJnsMutasi() {
		return this.jnsMutasi;
	}

	public void setJnsMutasi(String jnsMutasi) {
		this.jnsMutasi = jnsMutasi;
	}

	@Column(name = "NOMINAL", nullable = false, precision = 22, scale = 0)
	public int getNominal() {
		return this.nominal;
	}

	public void setNominal(int nominal) {
		this.nominal = nominal;
	}

	@Column(name = "SALDO_AKHIR", nullable = false, precision = 22, scale = 0)
	public double getSaldoAkhir() {
		return this.saldoAkhir;
	}

	public void setSaldoAkhir(double saldoAkhir) {
		this.saldoAkhir = saldoAkhir;
	}

	@Column(name = "NOTE", nullable = false)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TGL_MUTASI", nullable = false, length = 7)
	public Date getTglMutasi() {
		return this.tglMutasi;
	}

	public void setTglMutasi(Date tglMutasi) {
		this.tglMutasi = tglMutasi;
	}

	@Column(name = "NO_REK", unique = true, nullable = false, length = 10)
	public String getNoRek() {
		return noRek;
	}

	public void setNoRek(String noRek) {
		this.noRek = noRek;
	}

}
