package com.bca.minibank.entity;
// Generated Apr 24, 2020 11:11:46 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

/**
 * TbUsers generated by hbm2java
 */
@Entity
@Table(name = "TB_USERS")
public class TbUsers implements java.io.Serializable {

	private int idUser;
	private String username;
	private String password;
	private String nama;
	private String alamat;
	private String noHp;
	private String noKtp;
	private String role;
	private String statusUser;
	private String email;
	private String keterangan;
	
	private TbRekening tbRekening;
//	private Set<TbRekening> tbRekenings = new HashSet<TbRekening>(0);
	private Set<TbLogAdmin> tbLogAdmins = new HashSet<TbLogAdmin>(0);

	//Temporary(Gak masuk ke database)
//	private String confirmPassword;
//	private String tempPassword;
//	private String confirmPin;
//	private String tempPin;
	
	public TbUsers() {
	}

	public TbUsers(int idUser, String username, String password, String nama, String alamat, String noHp,
			String noKtp, String role, String statusUser, String email) {
		this.idUser = idUser;
		this.username = username;
		this.password = password;
		this.nama = nama;
		this.alamat = alamat;
		this.noHp = noHp;
		this.noKtp = noKtp;
		this.role = role;
		this.statusUser = statusUser;
		this.email = email;
	}

	public TbUsers(int idUser, String username, String password, String nama, String alamat, String noHp,
			String noKtp, String role, String statusUser, String email, String keterangan, TbRekening tbRekening, //Set<TbRekening> tbRekenings,
			Set<TbLogAdmin> tbLogAdmins) {
		this.idUser = idUser;
		this.username = username;
		this.password = password;
		this.nama = nama;
		this.alamat = alamat;
		this.noHp = noHp;
		this.noKtp = noKtp;
		this.role = role;
		this.statusUser = statusUser;
		this.email = email;
		this.keterangan = keterangan;
		this.tbRekening = tbRekening;
//		this.tbRekenings = tbRekenings;
		this.tbLogAdmins = tbLogAdmins;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "USERS_SEQ")
	@Column(name = "ID_USER", unique = true, nullable = false, precision = 22, scale = 0)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "USERNAME", nullable = false, length = 12)
	@NotBlank(message = "Username harus diisi")
	@Pattern(regexp = "^(?![0-9_.-])[a-z0-9_.-]{5,12}$", message = "Username tidak invalid, silahkan cek ketentuan pengisian username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", nullable = false)
	@Size(min = 8, max = 32, message = "Minimal 8 Karakter dan maksimal 32 karakter")
	@NotBlank(message = "Password harus diisi")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "NAMA", nullable = false, length = 30)
	@NotBlank(message = "Nama harus diisi")
	@Size(max = 30, message = "Maksimal 30 Karakter")
	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	@Column(name = "ALAMAT", nullable = false)
	@NotBlank(message = "Alamat harus diisi")
	@Size(max = 255, message = "Maksimal 255 Karakter")
	public String getAlamat() {
		return this.alamat;
	}

	public void setAlamat(String alamat) {
		this.alamat = alamat;
	}

	@Column(name = "NO_HP", nullable = false, length = 12)
	@NotBlank(message = "No. HP harus diisi")
	@Pattern(regexp = "^[0-9]{10,12}$", message = "Rentang No. HP 10 sampai 12 digit dan Harus Angka")
	public String getNoHp() {
		return this.noHp;
	}

	public void setNoHp(String noHp) {
		this.noHp = noHp;
	}

	@Column(name = "NO_KTP", nullable = false, length = 16)
	@NotBlank(message = "No. KTP harus diisi")
	@Pattern(regexp = "^[0-9]{16,16}$", message = "No. KTP 16 digit dan Harus Angka")
	public String getNoKtp() {
		return this.noKtp;
	}

	public void setNoKtp(String noKtp) {
		this.noKtp = noKtp;
	}

	@Column(name = "ROLE", nullable = false, length = 12)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "STATUS_USER", nullable = false, length = 10)
	public String getStatusUser() {
		return this.statusUser;
	}

	public void setStatusUser(String statusUser) {
		this.statusUser = statusUser;
	}

	@Column(name = "EMAIL", nullable = false, length = 30)
	@NotBlank(message = "Email harus diisi")
	@Size(max = 30, message = "Maksimal 30 Karakter")
	@Pattern(regexp = "^(.+)@(.+)$", message = "Pengisian email tidak valid")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "KETERANGAN")
	public String getKeterangan() {
		return this.keterangan;
	}

	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbUsers")
//	public Set<TbRekening> getTbRekenings() {
//		return this.tbRekenings;
//	}
//
//	public void setTbRekenings(Set<TbRekening> tbRekenings) {
//		this.tbRekenings = tbRekenings;
//	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy="tbUsers")
	public TbRekening getTbRekening() {
		return tbRekening;
	}

	public void setTbRekening(TbRekening tbRekening) {
		this.tbRekening = tbRekening;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbUsers")
	public Set<TbLogAdmin> getTbLogAdmins() {
		return this.tbLogAdmins;
	}

	public void setTbLogAdmins(Set<TbLogAdmin> tbLogAdmins) {
		this.tbLogAdmins = tbLogAdmins;
	}

	//////////////////////////////////////////
	//Getter Setter untuk Variabel Temporary//
	//////////////////////////////////////////
//	@NotBlank(message = "Confirm Password harus diisi")
////	@Pattern(regexp = "^[0-9]{16,16}$", message = "Confirm Password harus 16 digit dan Harus Angka")
//	public String getConfirmPassword() {
//		return confirmPassword;
//	}
//
//	public void setConfirmPassword(String confirmPassword) {
//		this.confirmPassword = confirmPassword;
//	}
//
//	@NotBlank(message = "Password harus diisi")
////	@Pattern(regexp = "^[0-9]{8,6}$", message = "Password harus 6 digit dan Harus Angka")
//	public String getTempPassword() {
//		return tempPassword;
//	}
//
//	public void setTempPassword(String tempPassword) {
//		this.tempPassword = tempPassword;
//	}
//	
//	@NotBlank(message = "Confirm PIN harus diisi")
//	@Pattern(regexp = "^[0-9]{6,6}$", message = "Confirm PIN harus 6 digit dan Harus Angka")
//	public String getConfirmPin() {
//		return confirmPin;
//	}
//
//	public void setConfirmPin(String confirmPin) {
//		this.confirmPin = confirmPin;
//	}
//
//	@NotBlank(message = "PIN harus diisi")
//	@Pattern(regexp = "^[0-9]{6,6}$", message = "PIN 6 harus digit dan Harus Angka")
//	public String getTempPin() {
//		return tempPin;
//	}
//
//	public void setTempPin(String tempPin) {
//		this.tempPin = tempPin;
//	}

}
